$(document).ready(function() {
    var display = function(selector, animation, next) {
        $('#error').hide();
        $('#error-label').hide();
        $('#headphones').hide();
        $('#headphones-label').hide();
        $('#' + selector).addClass('animated ' + animation[0]);
        $('#' + selector + '-label').addClass('animated ' + animation[1]);
        $('#' + selector).show();
        $('#' + selector + '-label').show();

        if (next) {
            $('#' + selector).one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend', function() {
                setTimeout(next, 1000);
            });
        }
    }

    var fill_text = function(l) {
        var a = {
            'fr': [
                "La banane est le fruit ou la baie dérivant de l’inflorescence du bananier. Les bananes sont des fruits très généralement stériles issus de variétés domestiquées. Les fruits des bananiers sauvages et de quelques cultivars domestiques contiennent des graines. Les bananes sont généralement jaunes lorsqu'elles sont mûres et vertes quand elles ne le sont pas. Les bananes constituent un élément essentiel du régime alimentaire de certaines régions. Les formes sauvages Musa acuminata et Musa balbisiana se rencontrent encore aujourd’hui dans une grande partie du Sud Est Asiatique, de l’Inde à la Papouasie-Nouvelle-Guinée. On retrouve encore dans ces régions des bananiers sauvages riches en graines et pauvres en pulpe dans les milieux ouverts (clairières, lisières des forêts). Le centre de domestication primaire semble être les hautes terres de Papouasie-Nouvelle-Guinée, il y a 6 950 à 6 440 ans avec M. acuminata. Des traces de production bananière pour une consommation humaine datant d'environ de cette époque en Nouvelle-Guinée.",
                "Un poney (féminin : ponette), cheval nain en Louisiane, est, selon la définition courante, un cheval de petite taille, avec une conformation et un tempérament particuliers. Il existe de nombreuses races de poneys différentes. Par rapport aux chevaux, les poneys présentent souvent une crinière épaisse, une queue et un pelage fournis, ainsi que des jambes proportionnellement plus courtes, un corps plus large, une ossature plus lourde, une encolure plus courte et épaisse, et une tête plus courte avec le front plus large. La Fédération équestre internationale (FEI) ne prend en compte que la taille pour définir ce qu'est un poney. Selon ses normes, tout cheval de moins d' 1,47 m au garrot (ou 1,48 m ferré) est classé 'poney', afin de faciliter les compétitions officielles.",
                "Cactus est le nom usuel des plantes de la famille des Cactaceae. On les appelle également cactées. Ce sont presque toutes des plantes grasses ou plantes succulentes, c'est-à-dire des plantes xérophytes qui stockent dans leurs tissus des réserves de 'suc' pour faire face aux longues périodes de sécheresse. Il ne faut pas confondre cactus et plante succulente : toutes les plantes succulentes ne sont pas des cactus. Ce sont des familles de plantes qui ont adopté les mêmes méthodes de lutte contre les périodes de sécheresse, comme les Asclepiadaceae ou les Crassulaceae. Certaines plantes de ces autres familles, par convergence des formes d'espèces soumises aux mêmes contraintes, ressemblent fortement aux cactus. C'est le cas par exemple des euphorbes cactiformes comme Euphorbia canariensis. Pour distinguer les vrais cactus des plantes qui leur ressemblent, il faut se reporter aux critères d'appartenance à la famille des Cactaceae. L'identification se fait par la présence d'aréoles, et, comme plus généralement en botanique, par les fleurs et les fruits."
            ],
            'en': [
                "A banana is an edible fruit produced by several kinds of large herbaceous flowering plants in the genus Musa. (In some countries, bananas used for cooking may be called plantains.) The fruit is variable in size, color and firmness, but is usually elongated and curved, with soft flesh rich in starch covered with a rind which may be green, yellow, red, purple, or brown when ripe. The fruits grow in clusters hanging from the top of the plant. Almost all modern edible parthenocarpic (seedless) bananas come from two wild species – Musa acuminata and Musa balbisiana. The scientific names of most cultivated bananas are Musa acuminata, Musa balbisiana, and Musa × paradisiaca for the hybrid Musa acuminata × M. balbisiana, depending on their genomic constitution. The old scientific name Musa sapientum is no longer used. Musa species are native to tropical Indomalaya and Australia, and are likely to have been first domesticated in Papua New Guinea. They are grown in at least 107 countries, primarily for their fruit, and to a lesser extent to make fiber, banana wine and banana beer and as ornamental plants.",
                "A pony is a small horse (Equus ferus caballus). Depending on context, a pony may be a horse that is under an approximate or exact height at the withers, or a small horse with a specific conformation and temperament. There are many different breeds. Compared to other horses, ponies often exhibit thicker manes, tails and overall coat, as well as proportionally shorter legs, wider barrels, heavier bone, thicker necks, and shorter heads with broader foreheads. The word 'pony' derives from the old French poulenet, meaning foal, a young, immature horse, but this is not the modern meaning; unlike a horse foal, a pony remains small when fully grown. However, on occasion, people who are unfamiliar with horses may confuse an adult pony with a foal.",
                "A cactus (plural: cacti, cactuses, or cactus) is a member of the plant family Cactaceae within the order Caryophyllales. The word 'cactus' derives, through Latin, from the Ancient Greek κάκτος (kaktos), a name originally used for a spiny plant whose identity is not certain. Cacti are native to the Americas, ranging from Patagonia in the south to parts of western Canada in the north—except for Rhipsalis baccifera, which also grows in Africa and Sri Lanka. Most cacti live in habitats subject to at least some drought. Many live in extremely dry environments, even being found in the Atacama Desert, one of the driest places on earth. Cacti show many adaptations to conserve water. Most species of cacti have lost true leaves, retaining only spines, which are highly modified leaves. As well as defending against herbivores, spines help prevent water loss by reducing air flow close to the cactus and providing some shade. Cactus spines are produced from specialized structures called areoles, a kind of highly reduced branch. Areoles are an identifying feature of cacti. As well as spines, areoles give rise to flowers, which are usually tubular and multipetaled."
            ],
            'it': [
                "Il banano (Musa L.) è una pianta della famiglia delle Musaceae. Il termine banana è applicato al frutto della pianta, che si sviluppa (nella specie e nelle varietà commestibili) in una serie di grappoli. Le banane pesano tipicamente 125 – 200 g, benché questo peso vari considerevolmente fra le differenti cultivar. Il frutto è commestibile per circa l'80%, il restante 20% è buccia; può essere consumato crudo o cotto. Quasi tutte le moderne banane partenocarpiche utilizzate a scopo alimentare provengono dalle specie Musa acuminata e Musa balbisiana. Il nome scientifico delle banane è Musa acuminata, Musa balbisiana o l'ibrido Musa acuminata × balbisiana, a seconda della costituzione del loro genoma. I vecchi nomi scientifici Musa sapientum e Musa paradisiaca non sono più in uso. Nella cultura popolare e nel commercio 'banana' di solito si riferisce alle morbide e dolci banane utilizzate come frutta. Invece le cultivar di Musa con frutti più duri e ricchi d'amido vengono talvolta chiamate 'platani', un prestito dello spagnolo plátano. Questa distinzione tuttavia è puramente arbitraria; le parole platano e banana sono spesso intercambiabili quando il tipo di frutto è desumibile dal contesto. In Italia possono sopravvivere alcune cultivar di banana. In particolare la cultivar comune di Sicilia è abbastanza rustica in Sicilia dove riesce a portare a maturazione i frutti.",
                "La Fédération Équestre Internationale ha stabilito che un cavallo può essere ufficialmente detto pony solo se misura meno di 151cm. Comunque, il termine 'pony' può essere utilizzato in generale per qualunque genere di cavallo dalle dimensioni ridotte, senza badare con esattezza alle sue dimensioni od alla razza; per di più, alcune razze di cavallo posseggono individui adulti sotto i parametri d'altezza per un pony ma che sono tuttavia considerati 'cavalli' ed hanno la possibilità di partecipare a competizioni ufficiali in qualità di cavalli. In Australia cavalli che misurano fra i 140 ed i 150 cm sono conosciuti come galloway. Coloro che hanno scarsa familiarità con i cavalli potrebbero confondere un pony adulto con un cavallo ancora giovane; sebbene un puledro che stia raggiungendo le dimensioni di un cavallo adulto possa essere non più alto di un pony durante il suo primo mese di vita, cavallo e pony sono decisamente diversi. Un pony può essere cavalcato ed essere messo a lavorare, mentre un puledro è generalmente troppo giovane per essere cavalcato o per essere utilizzato come animale da soma. È possibile distinguere un puledro da un pony a causa del fatto che le zampe del puledro sono più lunghe di quelle di un pony ed anche l'intera figura del giovane cavallo è più slanciata ed elastica.",
                "Le Cactaceae Juss., 1789 (chiamate anche cactacee, più comunemente cactus e, più raramente cacti al plurale) sono una famiglia di piante succulente (piante xerofite, adattate agli ambienti aridi mediante l'accumulo di acqua all'interno di tessuti succulenti) che comprende circa 3000 specie e 120 generi. Sono per lo più utilizzate come piante ornamentali, ma alcune sono anche piante da raccolto. I cactus fanno parte dell'ordine delle Caryophyllales, che include anche altri membri, come le barbabietole, gli spinaci, l'amaranto, i garofani, il rabarbaro, il grano saraceno, il plumbago e la bougainvillea. Le cactaceae sono piante inusuali e facilmente identificabili che sono riuscite ad adattarsi ad ambienti estremamente aridi e caldi, sviluppando diverse caratteristiche fisiologiche e anatomiche per conservare l'acqua. I loro fusti si sono adattati diventando succulenti e fotosintetici, mentre le foglie, molto spesso, sono diventate le spine, una delle caratteristiche più distintive delle piante di questa famiglia."
            ],
            'es': [
                "El nombre científico Musa × paradisiaca (o Musa paradisiaca) y los nombres comunes banano, plátano, cambur, topocho y guineo hacen referencia a un gran número de plantas herbáceas del género Musa, tanto híbridos obtenidos horticulturalmente a partir de las especies silvestres del género Musa acuminata y Musa balbisiana como cultivares genéticamente puros de estas especies. Clasificado originalmente por Linnaeus como Musa paradisiaca en 1753, la especie tipo del género Musa, estudios posteriores han llevado a la conclusión de que la compleja taxonomía del género incluye numerosos híbridos, de variada composición genética, y se ha desarrollado un sistema estrictamente sui géneris de clasificación para dar cuenta de esta variación. Sin embargo, de acuerdo con las reglas del Código Internacional de Nomenclatura Botánica, el nombre linneano cuenta con prioridad, y sigue siendo usado —tanto en su forma original como en la modificada Musa × paradisiaca, que indica que se trata de un híbrido— para designar genéricamente a estas variedades. En la nomenclatura vernácula a veces se traza una diferencia entre las bananas, consumidas crudas como fruta de postre, y los plátanos, que por su superior contenido en fécula deben asarse o freírse antes de su ingesta. La diferencia no se corresponde exactamente con ningún criterio genético; aunque las variedades con mayor presencia genética de M. balbisiana suelen estar comprendidas en este segundo grupo, no se puede determinar si una planta producirá plátanos o bananas simplemente por su constitución genética. La confusión aumenta por el hecho de que en otras regiones los términos se consideran perfectamente sinónimos (ver, más abajo, apartado sobre Etimología).",
                "Un poni, póney —esta segunda forma menos usada y por ello no recomendada por la Real Academia—, (ambas tomadas de pony en inglés o poney en francés, probablemente todas ellas procedentes de la palabra francesa obsoleta poulenet, diminutivo de poulain, ‘potro’, a su vez del francés antiguo pulain, y quizá a su vez del latín medieval pullamen, ‘animal joven’, derivada del latín clásico pullus), o jaca, es un caballo pequeño de unos 150 cm de altura máxima hasta la cruz, y un peso medio de 100 kg. Es muy rústico y resistente, con formas más o menos masivas, perfil recto y orejas triangulares en lugar de dirigidas hacia dentro como los caballos de mayor alzada.6 Las razas más puras y primitivas conservan caracteres de los equinos primitivos, como rayas a lo largo del lomo, o incluso en las patas, hocico harinoso, crines tupidas y semienhiestas y mucho carácter, lo que compensa su falta de alzada con otras razas de caballos. Se sabe que los antepasados de los actuales caballos eran aproximadamente de esta alzada, y a medida que se los fue domesticando y mejorando la especie, tomaron mayor altura a consecuencia de la selección humana. Los ponis están clasificados dentro de los cuatro tipos principales de caballos primitivos de Eurasia; los otros englobarían los antepasados de razas como los caballos árabes y similares, los caballos genéricos de silla que descendieron del tarpán y por último los antepasados de los caballos de sangre fría. Por tanto, las jacas o ponis son un tipo de caballo que aún conserva los caracteres primitivos.",
                "Las cactáceas (Cactaceae) son una familia de plantas suculentas y, en gran mayoría, espinosas, conocidas en conjunto como cactos o cactus. Esta familia es originaria de América. Sin embargo, hay una excepción, Rhipsalis baccifera, que está extendida en África tropical, Madagascar y Ceilán. Se cree que la colonización del Viejo Mundo por esta especie es relativamente reciente (unos cuantos cientos de años), probablemente transportada en el tracto digestivo de pájaros migratorios en forma de semillas o, según otra teoría, en forma de plantas adheridas a troncos impulsados por corrientes marinas. Muchas otras especies de cactáceas se han naturalizado, en condiciones similares a las de su hábitat, en otras partes del mundo, tras ser introducidas por el hombre. El mejor ejemplo es quizás Opuntia ficus-indica, especie que se encuentra plenamente integrada en la zona mediterránea. Fue introducida allí por sus frutos comestibles. Muchas plantas suculentas, tanto en el Viejo como en el Nuevo Mundo, tienen una notable semejanza con los cactus y, a menudo, son así llamadas en lenguaje corriente. Sin embargo, esto se debe a la evolución paralela, ya que ninguna de ellas está estrechamente emparentada con las cactáceas. La característica identificativa más clara de la familia de los cactus es la areola, una estructura especializada de donde surgen las espinas, los vástagos nuevos y, en muchas ocasiones, las flores."
            ],
            'de': [
                "Die Dessertbanane, auch Obstbanane oder kurz Banane (Musa × paradisiaca), ist eine Art aus der Gattung der Bananen; vor allem die Frucht vieler ihrer Sorten wird so genannt. Dessertbananen gehören zu den im deutschsprachigen Raum am meisten gegessenen Früchten. Die Banane stammt ursprünglich aus der südostasiatischen Inselwelt. 600 vor Christus wurde sie in buddhistischen und indischen Schriften erwähnt. Nach Afrika kam die Banane wohl mit den austronesischen Einwanderern, die Madagaskar vom heutigen Indonesien aus besiedelten und die auch Reis nach Madagaskar brachten. Von den Kanarischen Inseln, wo die Spanier sie schon 1400 auf Plantagen angepflanzt hatten, gelangte sie nach Amerika. 1502 gründeten portugiesische Siedler die ersten Plantagen in der Karibik und in Mittelamerika. In der Oeconomischen Encyclopädie (1773–1858) von J. G. Krünitz wird die Frucht von Musa × paradisiaca noch Paradiesfeige genannt. Weitere veraltete deutsche Bezeichnungen sind Adamsfeige und Schlauchapfel.",
                "Es gibt typische Ponyrassen, welche sich durch stämmigen Wuchs, reiches Langhaar, starke Nerven und Leichtfuttrigkeit auszeichnen. Beispiele für typische Ponyrassen sind Shetlandpony, Dartmoor-Pony, Exmoor-Pony, New-Forest-Pony, Isländer und Highland-Pony. Andere Ponyrassen sind auf Reitpferdepoints, beispielsweise raumgreifende Gänge und Springvermögen gezogen und werden im Ponysport eingesetzt. Beispiele hierfür sind Welsh-Pony, Connemara-Pony und Deutsches Reitpony. Diese Ponyrassen wurden mit Arabern veredelt. Die Fütterung von typischen Ponyrassen unterscheidet sich von der Fütterung von Warmblütern. Ein typisches Pony benötigt wesentlich weniger Kraftfutter als ein Warmblüter. Ohne Arbeit, in der Erhaltungsfütterung, können im Sommer eine gute Weide und im Winter Heu und Wasser genügen. Je nach Bedarf ist es angebracht, Mineralfutter zu geben. Eine große Gefahr geht von übermäßig fetten Weiden und zu viel Kraftfutter aus, die Hufrehe, Kreuzverschlag und Koliken auslösen können. Auch ein Übermaß an Mineralfutter kann Hufschäden verursachen.",
                "Kakteen sind ausdauernde Sträucher, seltener Bäume oder Geophyten. Fast alle Arten sind Stammsukkulenten, deren Sprossachsen stark angeschwollen sind. Die Wurzeln sind meist faserig oder bilden bei Pflanzen mit nur geringer Stammsukkulenz manchmal sukkulente Knollen oder Rüben. Die Hauptsprosse stehen, häufig charakteristisch für bestimmte Gattungen, einzeln oder verzweigen von den Basen oder weiter oben. Hauptsprosse und Zweige wachsen meist aufrecht oder aufstrebend, manchmal auch kriechend oder hängend. Die Sprosse sind zylindrisch oder zu Platykladien abgeflacht und tragen häufig gut ausgebildete Rippen oder spiralig arrangierte Warzen. Areolen, die stark reduzierte Kurztriebe darstellen, stehen auf zylindrischen oder abgeflachten Sprossen meist gefeldert verteilt oder sonst auf den Erhöhungen der Rippen oder Warzen. Sie sind filzig und tragen Dornen, die umgewandelte Blätter darstellen, sowie häufig auch Wolle oder Borsten. Filz und Dornen sind bei jungen Sämlingen immer vorhanden, werden aber manchmal später abgeworfen oder von erwachsenen Pflanzen nicht mehr gebildet. Die den Areolen entspringenden Laubblätter sind manchmal vollständig ausgebildet (Unterfamilie Pereskioideae), häufig pfriemförmig, sukkulent und kurzlebig (Unterfamilien Opuntioideae und Maihuenioideae), fehlen aber meist völlig (Unterfamilie Cactoideae). Nebenblätter sind nicht vorhanden."
            ]
        }[l.data];
        $('#text').text(a[~~(Math.random() * (a.length))]);
    }

    display('headphones', ["fadeInDown", "fadeInUp"]);
    $('#fr').click('fr', fill_text);
    $('#en').click('en', fill_text);
    $('#it').click('it', fill_text);
    $('#es').click('es', fill_text);
    $('#de').click('de', fill_text);

    setTimeout(function() {
        var errorCallback = function(err) {
            display("error", ["fadeInDown", "fadeInUp"]);
        };

        navigator.media = (navigator.getUserMedia
        || navigator.webkitGetUserMedia
        || navigator.mozGetUserMedia
        || navigator.msGetUserMedia);

        var context = new (window.AudioContext || window.webkitAudioContext)();

        if (navigator.media && context) {
            navigator.media({audio: true}, function(stream) {
                var microphone = context.createMediaStreamSource(stream);
                var delay = context.createDelay();
                var gain = context.createGain();
                delay.delayTime.value = 0.2;
                gain.gain.value = 1.8;

                microphone.connect(delay);
                delay.connect(gain);
                gain.connect(context.destination);

                display('speak', ["fadeInDown", "fadeInUp"], function() {
                    display('speak', ["fadeOutUp", "fadeOutDown"], function(){
                        fill_text({data:'en'});
                        $('#speak').hide();
                        $('#speak-label').hide();
                        $('#text').show();
                        $('.sidebar').show();
                        $('#text').addClass('animated fadeInDown');
                    });
                });
            }, errorCallback);
        } else {
            errorCallback();
        }
    }, 2000);
});